events {
    worker_connections 1024;
}

http {
    # Mappa i log per vederli facilmente su Docker
    access_log /dev/stdout;
    error_log /dev/stderr;

    upstream yolo_backend {
        # Punta esattamente al nome del container definito nel compose e alla sua porta interna
        server yolo-api:8000;
    }

    server {
        listen 80;
        server_name localhost; 

        # Fondamentale per la Computer Vision: permette upload di immagini fino a 20 MB
        client_max_body_size 20M;

        location / {
            proxy_pass http://yolo_backend;
            
            # Passaggio degli header originali
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Timeout estesi per l'elaborazione del tensore e l'inferenza YOLO
            proxy_connect_timeout 60s;
            proxy_read_timeout 120s;
            proxy_send_timeout 120s;
        }
    }
}